### ISSUE TITLE
 Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by jakegibs617** [kumavis/browser-stdout#6]
Working on adding unit tests to my customcke5plugin ran npm run test -- -f customcke5plugin 
and got this error relating to browser-stdout

21 09 2023 09:35:27.847:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
21 09 2023 09:35:27.848:INFO [launcher]: Launching browsers CHROME_LOCAL with concurrency unlimited
21 09 2023 09:35:27.852:INFO [launcher]: Starting browser Chrome
21 09 2023 09:35:31.707:INFO [Chrome 117.0.0.0 (Mac OS 10.15.7)]: Connected on socket SBReu4L0T_05ZWRcAAAB with id 65260043
Chrome 117.0.0.0 (Mac OS 10.15.7) ERROR
  Uncaught TypeError: Cannot read properties of undefined (reading 'call')
  at node_modules/browser-stdout/index.js:13:1 <- entry-point.2276825919.js:66486:18

  TypeError: Cannot read properties of undefined (reading 'call')
      at new BrowserStdout (node_modules/browser-stdout/index.js:13:1 <- entry-point.2276825919.js:66486:18)
      at BrowserStdout (node_modules/browser-stdout/index.js:10:1 <- entry-point.2276825919.js:66483:48)
      at ./node_modules/mocha/browser-entry.js (node_modules/mocha/browser-entry.js:10:42 <- entry-point.2276825919.js:101474:101)
      at __webpack_require__ (webpack/bootstrap:19:1 <- entry-point.2276825919.js:137797:42)
      at ./packages/ckeditor5-mailtotag/tests/mailtotag.js (packages/ckeditor5-customcke5plugin/tests/customcke5plugin.js:1:26 <- entry-point.2276825919.js:101297:26)
      at __webpack_require__ (webpack/bootstrap:19:1 <- entry-point.2276825919.js:137797:42)
      at entry-point.2276825919.js:137902:214
      at entry-point.2276825919.js:137917:3
      at entry-point.2276825919.js:137919:12

**Comment by jakegibs617** [comment]
I did find the error went away when I removed this from my test file:

const { describe, it } = require('mocha');
